manifest:
  remotes:
    - name: zmk-shield-logos 
      url-base: https://github.com/brichar01/zmk-shield-logos
  projects:
    # Together with the above defined remote, this refers to a module located at
    # https://github.com/remote-name/repository-name
    - name: zmk-shield-logos
      remote: brichar01 
      # This points to a west manifest file in the remote module for further imports
      import: west.yml
